# Generated by Django 3.2 on 2022-12-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PulsarProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vendor', models.IntegerField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('status', models.TextField(choices=[(1, 'В наличии'), (2, 'Под заказ'), (3, 'Ожидается поступление'), (4, 'Нет в наличии'), (5, 'Не производится')])),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
