# Generated by Django 3.2 on 2022-12-14 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shop.fields
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pulsarproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='pulsarproduct',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pulsarproduct',
            name='status',
            field=models.TextField(choices=[('В наличии', 'В наличии'), ('Под заказ', 'Под заказ'), ('Ожидается поступление', 'Ожидается поступление'), ('Нет в наличии', 'Нет в наличи'), ('Не производится', 'Не производится')]),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField(blank=True, default=0, null=True, verbose_name='Height')),
                ('width', models.IntegerField(blank=True, default=0, null=True, verbose_name='Width')),
                ('image', shop.fields.WEBPField(height_field='height', upload_to=shop.models.image_folder, verbose_name='Image', width_field='width')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
