# Generated by Django 3.2 on 2022-12-14 13:19

from django.db import migrations
import shop.fields
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20221214_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pulsarproduct',
            name='image',
            field=shop.fields.WEBPField(blank=True, null=True, upload_to=shop.models.image_folder, verbose_name='Image'),
        ),
    ]
